# =========================
# Stage 1: Build frontend
# =========================
FROM node:22-bookworm-slim AS assets

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build


# =========================
# Stage 2: Laravel + FrankenPHP
# =========================
FROM dunglas/frankenphp:php8.5-bookworm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo_mysql \
        mbstring \
        bcmath \
        exif \
        pcntl \
        intl \
        gd \
        zip \
        opcache \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

COPY . .

# Copy hasil build Vite
COPY --from=assets /app/public/build ./public/build

RUN chown -R www-data:www-data \
    storage \
    bootstrap/cache

ENV APP_ENV=production
ENV APP_DEBUG=false

CMD ["sh", "-c", "frankenphp php-server --root /app/public --listen :${PORT:-80}"]